image: Ubuntu

stack: jdk 11

services:
  - docker
  - mysql
  - postgresql10

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - docker-compose up -d
  - java "-Dspring.datasource.url=jdbc:mysql://localhost:3306/app" -jar artifacts/aqa-shop.jar -P:profile=test
  - ./gradlew test -Dselenide.headless=true --info

build_script:
  - npm start
