image: Ubuntu

stack: jdk 11

services:
  - docker

branches:
  only:
    - main

build: off

install:
  - docker-compose up --build
  - chmod +x gradlew
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar artifacts/aqa-shop.jar



build_script:
  - ./gradlew test -Dselenide.headless=true --info
 