image: Ubuntu

stack: jdk 11
environment:
  SPRING_CREDIT_GATE_URL: http://localhost:9999/credit
  SPRING_PAYMENT_GATE_URL: http://localhost:9999/payment
  SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/app
  SPRING_DATASOURCE_USERNAME: app
  SPRING_DATASOURCE_PASSWORD: pass

services:
  - docker
  - mysql
  - postgresql10

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - docker-compose up -d
  - java "-Dspring.datasource.url=jdbc:mysql://localhost:3306/app" -jar artifacts/aqa-shop.jar
  

build_script:
  - .\gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/app
  - ./gradlew test -Dselenide.headless=true --info
  - npm start
