image: Ubuntu

stack: jdk 11

environment:
  spring.credit-gate.url: http://localhost:9999/credit
  spring.payment-gate.url: http://localhost:9999/payment
  spring.datasource.url: jdbc:mysql://localhost:3306/app
  spring.datasource.username: app
  spring.datasource.password: pass

services:
  - docker
  - mysql
  - postgresql10

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - docker-compose up -d
  - java "-Dspring.datasource.url=jdbc:mysql://localhost:3306/app" -jar artifacts/aqa-shop.jar
  

build_script:
  - .\gradlew clean test -Ddb.url=jdbc:mysql://localhost:3306/app
  - ./gradlew test -Dselenide.headless=true --info
  - npm start
