image: Ubuntu

stack: jdk 11

services:
  - docker

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - docker-compose up --build
  - java -jar artifacts/app-ibank-build-for-testers.jar -P:profile=test
build_script:
  - npm start
  - ./gradlew test -Dselenide.headless=true --info