version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
    - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  mysql:
    image: mysql:8.0.31
    restart: always
    ports:
    - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  nodejs:
    build: ./gate-simulator
    ports:
    - '9999:9999'